### ISSUE TITLE
Omni completion (^O^N^P) Pattern not found

### ISSUE THREAD

**Issue by eater** [dbeniamine/todo.txt-vim#11]
I'm trying to omni-complete a project name. I've set `omnifunc=todo#Complete`. I type `+<C-X><C-O>` and Vim gives me the above error. Any suggestions?

**Comment by dbeniamine** [comment]
Can you give me a bit more of context ?

If you haven't any project in your todo.txt this is normal as the pattern `+something` does not exists.
If their are some lines with `+project` in it this shouldn't happen, in that case can you give me a minimalistic todo.txt that produces the bug ?

**Comment by eater** [comment]
Here's a todo.txt file where I'm seeing the bug:

```
glass                                   +glass due:2017-03-30
write Jacobsen                          +spiciness
reply to Dan                            +pitches 
reply to Anne                        +pitches 
reply to Mara                         +pitches 
find spicy sources                      +spiciness
read Dana                              +wine
write Ella back  
reply to beet genetics q  
juices                                  +acid
```

**Comment by dbeniamine** [comment]
I can reproduce the bug with this file, I'm looking for a solution

**Comment by dbeniamine** [comment]
The problem was due to the complete function ignoring lines without priority or complete mark, which was not very smart ...
Commit f77215ca809114c7b1e5b1a9a6d035650ac1eee1 fixes it

**Comment by eater** [comment]
Fixed! Thanks.
