### ISSUE TITLE
Sorting by due date moves the cursor to the end of the list

### ISSUE THREAD

**Issue by fretep** [dbeniamine/todo.txt-vim#15]
This may be by design, but it strikes me as a little counter intuitive. When sorting by due date, you end up positioned at the end of the list.

I would have preferred the cursor to be placed at either the top of the list, the last task with a due date, the task the cursor was on at the time the sort was invoked, or the first/last task with today as a due date.

I'm not sure which of those I'd actually prefer at the moment, only that any of them would be preferable (for me) to the end of the list.

What are other peoples thoughts on this?

EDIT: Sorry, it was my todo.txt file confusing me, a little more looking into this, and it places you on the last task with a due date, which is probably ok for people who don't have due:dates on every task like I do.

Having put a little more thought into it, I now think the ideal would be to position the cursor on the task as close to todays date as possible. That, I realize would probably not be that easy to code. I'm still interested on others thoughts on where the cursor should be placed?

**Comment by fretep** [comment]
Thinking more on this, the position of the cursor after the sort is probably very much a user preference, but I think the default would be better to be the top of the buffer, i.e. the most outstanding task, not the bottom of the tasks with a due date as that is probably your least outstanding task.

In #16 I've added a new global variable so users can set their preference on the cursor position after the sort:

let g:TodoTxtSortDueDateCursorPos = "top"

"top" (default): The first line of the buffer, i.e. your most outstanding task
"lastdue": The last task with a due:date set
"notoverdue": The first task that is not overdue (requires #13)
"bottom": The last line of the buffer

I'd still like to hear from anyone with an opinion on this.

**Comment by dbeniamine** [comment]
Good idea and good work, I was going to propose to use a Global variable to set the position of the cursor. I'll review you're code and merge it !

**Comment by dbeniamine** [comment]
I close the issue as I merged your work in 0.8.

Thanks for your help :) !
