### ISSUE TITLE
SortDue() does not correctly sort tasks with a due:date starting in column 1

### ISSUE THREAD

**Issue by fretep** [dbeniamine/todo.txt-vim#17]
i.e.:
due:2017-09-12 Task
Task due:2017-09-30

will sort to:
Task due:2017-09-30
due:2017-09-12 Task

I think this is due to the "^[^x]" regex in the global and sort commands, which I believe will consume the first character of the line. This looks challenging to solve in the RegExp, I had a crack at a lookarounds, but I wasn't successful.

Thinking about this a bit more, I'd probably tackle this by reverting to the RegExp I submitted in my previous pull request, and then after the sort, do a :global/^x/move$

That has the benefit? of moving completed tasks to the bottom of the list. I'm not sure that is desirable however. Given previously completed tasks were sorted into the active tasks, and only in this last commit did the completed tasks get sorted below (but not to the bottom) of the list, it is probably acceptable (at least in my mind) to change the behavior.

I'm also not 100% sure that a line starting with due:date is valid as this scenario is not specifically called out in the todo.txt spec, however, project and contexts are valid in this position, so I'd imagine due:dates probably should be too.

I'm happy to do a pull request with the changes to sort completed tasks to the bottom in todo#SortDue(). I've not had a chance to look at how the other sort methods handle this scenario.

Thoughts?

**Comment by dbeniamine** [comment]
That's a good point but we can easily fix it just by concatenating your original regex with the non-done task test, i.e: `/^[^x]\&^.*\<due:/`

**Comment by fretep** [comment]
Oh nice, I didn't know that RegExp. However, it will match tasks starting with "x", not that many words would start with "x", I can only come up with abbreviations like "xtra" or  "xtract". Probably not a big deal.

In the meantime I've come up with https://github.com/fretep/todo.txt-vim/commit/0ed7d4848ea73d894cfe11e2fccec987b965f58a, I'm still testing, but it seems solid. It sorts the completed tasks to the bottom. Thoughts on that? Happy to refactor to use the RegExp syntax you came up with to keep the tasks in situ.

**Comment by dbeniamine** [comment]
Concerning your first point, I guess that matching only lines starting with a `x`separated by spacing characters should do the trick : `^[^\<\s*x\s*\>]`.

Nevertheless, I agree that we should make sure that after a sort, done tasks are at the bottom, thus  it is indeed preferable to use the move.

**Comment by fretep** [comment]
The SortDue() function is now passing all the tests I can think of throwing at it. Thanks for your help with this.
