### ISSUE TITLE
SortDue() minor bugs

### ISSUE THREAD

**Issue by fretep** [dbeniamine/todo.txt-vim#18]
My last pull request has a bug with the cursor positioning set to g:TodoTxtSortDueDateCursorPos="notoverdue" when there are no overdue tasks (sorry, not sure how I missed this). I'll get a pull request to fix this soon.

Also, g:TodoTxtSortDueDateCursorPos="lastdue" fails when there are completed tasks (i.e. it moves to the completed task). I'll fix this at the same time as the above.

**Comment by dbeniamine** [comment]
I also missed it, I'll wait for your next PR
