### ISSUE TITLE
Enhancement Request - more flexible file naming?

### ISSUE THREAD

**Issue by ultrablue** [dbeniamine/todo.txt-vim#2]
Hey:

Would it be useful if todo.txt-vim worked on files that had todo.txt as *part* of the name? Eg: 2015-07-06-todo.txt or todo-2015-07-06.txt? Would it be difficult to add?

Thanks!
Greg

**Comment by dbeniamine** [comment]
Hi,

I think that the commit message resume the modifications:


    More flexible file naming (Request #2)
    
    CHG: More flexible file naming files matching one of the following are todo
    files:
        YYYY-MM-[Tt]odo.txt
        YYYY-MM-DD[Tt]odo.txt
        [Tt]odo-YYYY-MM.txt
        [Tt]odo-YYYY-MM-DD.txt
        [Tt]odo.txt
        [Tt]oday.txt
        YYYY-MM-[Dd]one.txt
        YYYY-MM-DD[Dd]one.txt
        [Dd]one-YYYY-MM.txt
        [Dd]one-YYYY-MM-DD.txt
        [Dd]one.txt
        [Dd]one-[Tt]oday.txt
     Moreover, remove complete tasks (<LocalLeader>D) moves the task to the
     done.txt file corresponding to the current todo.txt, aka if you are editing
     2015-07-07-todo.txt, the done file while be 2015-07-07-done.txt.
     This behaviour can be cancelled by fixing the done filename using
     g:TodoTxtForceDoneName

See the Readme/documentation for more infos.

Enjoy,

David
