### ISSUE TITLE
Toggling completion on tasks with priority does not conform to todo.txt rules

### ISSUE THREAD

**Issue by fretep** [dbeniamine/todo.txt-vim#21]
When toggling the completion state of a task using `Leader-x` (`DoToggleMarkAsDone`), the handling of the priority is not consistent with todo.txt rules.

As per [todo.txt](https://github.com/todotxt/todotxt/) rules, completed tasks should have a completed date immediately following the "x ".

> Rule 2: The date of completion appears directly after the x, separated by a space.

It continues to say:

> Many Todo.txt clients discard priority on task completion. To preserve it, use the key:value format described below (e.g. pri:A)

So, a task such as:

```
(A) 2017-09-01 Test task
```

Should complete looking like:

```
x 2017-09-19 2017-09-01 Test task pri:A
```

or maybe stripping the priority

```
x 2017-09-19 2017-09-01 Test task
```

or maybe perhaps bending the rules a little

```
x 2017-09-19 2017-09-01 (A) Test task
```

but specifically not how it is currently being handled:

```
x (A) 2017-09-19 2017-09-01 Test task
```

or

```
x 2017-09-19 (A) 2017-09-01 Test task
```

Additionally, currently when toggling the completion a task with a priority multiple times, the format is broken as per below, each line representing one additional toggle.

```
(A) 2017-09-01 Test task
x (A) 2017-09-19 2017-09-01 Test task
x 2017-09-19 x (A) 2017-09-19 2017-09-01 Test task
x (A) 2017-09-19 2017-09-01 Test task
```

**Comment by dbeniamine** [comment]
I agree that current behavior is inconsistent and must be fixed.

I think preserving the priority is required if we want a correct toggle / untoggle behavior, so we should use the `pri:A`.
Here is an example of what we should obtain with a toggle / untoggle done :

    (A) 2017-09-01 Test task
    x 2017-09-19 2017-09-01 Test task pri:A
    (A) 2017-09-01 Test task

**Comment by fretep** [comment]
Nice work, thanks!
