### ISSUE TITLE
Handling of leading white space is not consistent

### ISSUE THREAD

**Issue by fretep** [dbeniamine/todo.txt-vim#23]
While looking over the code, I noticed that some operations allow leading white space on a line, while others do not.

The todo.txt rules are not clear (at least to me) on the use of leading white space. I think all operations and highlighting should be consistent, so perhaps we need to take a stance one way or the other and patch the code.

Thoughts?

Example:

```
 x 2017-09-20 This will not be highlighted as complete, but it will toggle with <Leader>x as if it is
```

**Comment by dbeniamine** [comment]
From my understanding of the rules, a line should not start with a space. If we highlight a line starting with a space, people will behave as this was allowed on the todo.txt rules which might, at some point, result in incompatibilities. Thus I think we should just not toggle your example.

**Comment by fretep** [comment]
Agreed, thanks for fixing.
