### ISSUE TITLE
Fold text and expression for folding on context

### ISSUE THREAD

**Issue by arecarn** [dbeniamine/todo.txt-vim#30]
Just thought I would share a snipped to vimL that I have in my .vimrc for a todo.txt fold expression and fold text for folding on context. I often do a hierarchical sort first by context then priority, so this works out great for me, but isn't always helpful with different types of sorting. 

Maybe it can give you some code / ideas if you want to add a similar feature to the plugin.

```
augroup TODO_TXT
    autocmd!
    autocmd BufNewFile,BufRead *todo.txt,*done.txt set filetype=todo
    autocmd BufNewFile,BufRead todo*.txt,done*.txt set filetype=todo
    autocmd FileType todo call s:todo_txt_settings()
augroup END

function! s:get_context(line) abort "{{{3
    return matchstr(getline(a:line), '@[^ ]\+')
endfunction "}}}3

function! Todo_fold_text(foldchar) abort "{{{3
    let line = s:get_context(v:foldstart)
    let lines_count = v:foldend - v:foldstart + 1
    let lines_count_text = '| ' . printf('%10s', lines_count . ' todos') . ' |'
    let foldtextstart = strpart(line, 0, (winwidth(0)*2)/3)
    let foldtextend = lines_count_text . repeat(a:foldchar, 8)
    let foldtextlength = strlen(substitute(foldtextstart . foldtextend, '.', 'x', 'g')) + &foldcolumn
    return foldtextstart . repeat(a:foldchar, winwidth(0)-foldtextlength) . foldtextend
endfunction "}}}3

function! Todo_fold(lnum) abort "{{{3
    let this_context = s:get_context(a:lnum)
    let next_context = s:get_context(a:lnum - 1)

    let fold_level = '0'

    if this_context ==# next_context
        let fold_level = '1'
    else
        let fold_level = '>1'
    endif

    return fold_level
endfunction "}}}3

function! s:todo_txt_settings() abort "{{{3
    setlocal foldmethod=expr
    setlocal foldexpr=Todo_fold(v:lnum)
    setlocal foldtext=Todo_fold_text('_')
endfunction "}}}3
```

**Comment by dbeniamine** [comment]
Hello,

Doing some folding sounds like a good idea, I think it could be a plus for the plugin. I think that we should be able to fold on  both context and project and the hierarchy between the level of folds should be determined by the cal to hierarchical sort.

If you want to hack some more on this topic feel free to do a Pull Request.

In any case thanks for the snippet !

David

**Comment by arecarn** [comment]
I played with that initially but ran into some difficulty implementing it correctly. A simpler approach would be to fold on the primary sort in the sort hierarchy.

For example when sorting on context then priority then fold on only context or when sorting on project then priority then fold on project.

**Comment by dbeniamine** [comment]
I must miss something because it doen't seem that hard to me : supposing that we sorted on context than projects, if we are on line 0 or if the previous line is a different context, than we are at fold level 1 and we fold all the context, else we are at fold level 2 and we fold the project.

So from your code we would just have to adapt a bit get_context and add a get_project plus one script level variable to know if we search for projects first than context.

**Comment by dbeniamine** [comment]
Ok then I'll give it a try

**Comment by dbeniamine** [comment]
I've merged your code in a way that preserve retro compatibility.

I found the tricky part : guessing the hierarchy before any sort is done ...

For now, I suppose we sort on context until a hierarchichal sort is done.

**Comment by arecarn** [comment]
It works great thanks! Thanks for your work!
