### ISSUE TITLE
Priority sorting doesn't seem to work as I'd expect

### ISSUE THREAD

**Issue by PhilT** [dbeniamine/todo.txt-vim#32]
When pressing `\s` to sort I get the following order:

```
(A) some high priority task
A task
(B) another task
```

I'd expect to see (A), (B) and then non-prioritised tasks after them. I suppose I could just map `<localleader>s` to `:sort<CR>` but wondered if I'm missing a feature.

I think what I'd really like to see is (A),(B),(C), then tasks with a due date and then other tasks. Is something like this possible?

Loving this fork. It's a great extension of freitass' work. Thanks for making this.

**Comment by dbeniamine** [comment]
That was a bug indeed, thanks for reporting it :+1:
