### ISSUE TITLE
Using hasmapto() wrong, is causing problems

### ISSUE THREAD

**Issue by arecarn** [dbeniamine/todo.txt-vim#4]
I was having trouble with some of the filetype mappings and saw that hasmapto() was being used wrong

see https://github.com/freitass/todo.txt-vim/issues/42

**Comment by dbeniamine** [comment]
Hi,

Thanks for your input, I fixed that in commit 41a75a8f50c073a47c405de9bcff7fb63968be35.

To disable mappings, add the following line to your vimrc:

    let g:Todo_txt_do_not_map=1

David

**Comment by arecarn** [comment]
Great! Thanks for the fix.

**Comment by dbeniamine** [comment]
You're welcome, the bug also affected two other of my plugins so your comment helped a lot !
