### ISSUE TITLE
Problem with the docs

### ISSUE THREAD

**Issue by ultrablue** [dbeniamine/todo.txt-vim#6]
Hello:
Under the sort section, this appears:

<LocalLeader>s@ : Sort the file on @Contexts
<LocalLeader>s@ : Sort the file on due dates

They're duplicates.

Thanks!
Greg

**Comment by dbeniamine** [comment]
Hi,

This is a typo  ̀<LocalLeader>s@` sort on context, it's  ̀<LocalLeader>sd` for due dates.
It's fixed by commit b6d5dc6bb969cc9ac1a1fb564255f42746a8e775

Thanks,
David
