### ISSUE TITLE
Unknown Function: todo#complete

### ISSUE THREAD

**Issue by witeshadow** [dbeniamine/todo.txt-vim#7]
on Mint I've installed via Vizardry, and everything seems to work BUT the "+" and "@" completion.
I get: 

` E117: Unknown function: todo#complete `

**Comment by dbeniamine** [comment]
Hi,
It seems there was an error on the readme, the function name is `todo#Complete` with a caps `C` not `todo#complete`

**Comment by witeshadow** [comment]
Great!  I'm no longer getting that error but it is still not expanding for me.

**Comment by dbeniamine** [comment]
After a few tests it seems that the completion list is not complete and can be empty for very small files, I'll fix this. Still can you attach me a file that cause you troubles ?

**Comment by dbeniamine** [comment]
It should have been fixed, can you update todo.txt-vim and tell me if it works ?

With Vizardry it should be something like `:Evolve todo.txt-vim`, still you will need to restart vim after that as Vizardry can't update autoloaded files for now ...
