### ISSUE TITLE
Python Annoyance

### ISSUE THREAD

**Issue by kurumushi** [dbeniamine/todo.txt-vim#8]
Every single time I open a flie I am reminded that I don't have python support and have to press enter. Can this be either somehow changed into a one time message?

**Comment by dbeniamine** [comment]
Hum sorry about that, I should have removed this warning while importing the support for due dates. For now I just removed the echo in commit ca8ae307d3bf863146147eccb20af5e3c23ba4e6. But I think that I will try to port the overdue date support to vimL as soon as I have some time to do it.
